apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-sync
  namespace: cert-manager
  labels:
    app: cert-manager
    managed-by: gitops
    purpose: cert-sync
spec:
  # Run daily at 2 AM UTC (adjust timezone as needed)
  # Since cert-manager renews 30 days before expiration, daily sync is sufficient
  schedule: "0 2 * * *"
  # Keep last 3 successful jobs and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  # Start job only if previous job has completed
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # Job should complete within 5 minutes
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app: cert-manager
            managed-by: gitops
            purpose: cert-sync
        spec:
          # Use service account with permissions to read secrets from rancher-manager
          # and write secrets to downstream clusters
          serviceAccountName: cert-sync
          restartPolicy: OnFailure
          containers:
          - name: cert-sync
            # Use alpine/k8s which has kubectl, then install jq
            image: alpine/k8s:1.29.4
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              # Install jq (required by sync script)
              apk add --no-cache jq bash
              # Run sync script
              /scripts/sync-certs.sh
            env:
            - name: KUBECONFIG
              value: /kubeconfig/config
            volumeMounts:
            - name: sync-script
              mountPath: /scripts
              readOnly: true
            - name: kubeconfig
              mountPath: /kubeconfig
              readOnly: true
          volumes:
          - name: sync-script
            configMap:
              name: cert-sync-script
              defaultMode: 0755
          - name: kubeconfig
            secret:
              secretName: cert-sync-kubeconfig
              defaultMode: 0600
