#!/bin/bash
#
# Sync TLS certificates from rancher-manager cluster to downstream clusters
#
# This script copies TLS secrets generated by cert-manager on rancher-manager
# to downstream clusters (nprd-apps, poc-apps, prd-apps), so only rancher-manager
# requests certificates from Let's Encrypt.
#
# Secrets to copy:
# - cert-manager/wildcard-dataknife-net-tls
# - kube-system/wildcard-dataknife-net-tls (for nginx default SSL)
#
# Usage:
#   ./sync-certs-from-rancher-manager.sh [target-cluster]
#   If target-cluster is not specified, syncs to all downstream clusters
#
# Prerequisites:
#   - kubectl configured with contexts: rancher-manager, nprd-apps, poc-apps, prd-apps
#   - Secrets must exist on rancher-manager cluster
#
# Exits non-zero if any cluster failed to sync (other clusters are still attempted).
#

set -uo pipefail

SOURCE_CLUSTER="rancher-manager"
DOWNSTREAM_CLUSTERS=("nprd-apps" "poc-apps" "prd-apps")
KUBECTL_TIMEOUT="${KUBECTL_TIMEOUT:-30s}"

# Items to copy: "source-namespace/secret-name[:target-namespace]"
# (target namespace defaults to the source namespace)
SYNC_ITEMS=(
    "cert-manager/wildcard-dataknife-net-tls"
    "cert-manager/wildcard-dataknife-net-tls:kube-system"
)

kc() {
    kubectl --request-timeout="${KUBECTL_TIMEOUT}" "$@"
}

# copy_secret <target-ctx> <source-ns> <secret-name> <target-ns>
# Returns non-zero unless the secret was applied and read back with matching tls.crt.
copy_secret() {
    local target_ctx="$1" src_ns="$2" name="$3" dst_ns="$4"
    local src_json manifest out want got

    echo "  Copying ${SOURCE_CLUSTER}:${src_ns}/${name} -> ${target_ctx}:${dst_ns}/${name}..."

    if ! src_json=$(kc --context="${SOURCE_CLUSTER}" get secret -n "${src_ns}" "${name}" -o json 2>&1); then
        echo "    ❌ Cannot read ${src_ns}/${name} on ${SOURCE_CLUSTER}: ${src_json}"
        return 1
    fi

    if ! manifest=$(jq -c --arg ns "${dst_ns}" '{
        apiVersion: "v1",
        kind: "Secret",
        metadata: {
            name: .metadata.name,
            namespace: $ns,
            labels: (.metadata.labels // {}),
            annotations: ((.metadata.annotations // {})
                | del(."kubectl.kubernetes.io/last-applied-configuration"))
        },
        type: .type,
        data: .data
    }' <<<"${src_json}"); then
        echo "    ❌ Failed to build manifest for ${src_ns}/${name}"
        return 1
    fi

    if ! out=$(kc --context="${target_ctx}" apply -f - <<<"${manifest}" 2>&1); then
        echo "    ❌ Apply to ${target_ctx}:${dst_ns}/${name} failed: ${out}"
        return 1
    fi

    want=$(jq -r '.data["tls.crt"] // ""' <<<"${src_json}")
    if ! got=$(kc --context="${target_ctx}" get secret -n "${dst_ns}" "${name}" -o jsonpath='{.data.tls\.crt}' 2>&1); then
        echo "    ❌ Read-back of ${target_ctx}:${dst_ns}/${name} failed: ${got}"
        return 1
    fi
    if [[ -z "${want}" || "${want}" != "${got}" ]]; then
        echo "    ❌ ${target_ctx}:${dst_ns}/${name} tls.crt does not match source after apply"
        return 1
    fi

    echo "    ✅ ${target_ctx}:${dst_ns}/${name} synced (${out})"
}

# sync_to_cluster <target-cluster>: returns the number of failed items
sync_to_cluster() {
    local target_cluster="$1" item src src_ns name dst_ns failures=0

    echo ""
    echo "🔄 Syncing certificates to ${target_cluster}..."

    for item in "${SYNC_ITEMS[@]}"; do
        src="${item%%:*}"
        src_ns="${src%%/*}"
        name="${src##*/}"
        dst_ns="${src_ns}"
        if [[ "${item}" == *:* ]]; then
            dst_ns="${item##*:}"
        fi
        copy_secret "${target_cluster}" "${src_ns}" "${name}" "${dst_ns}" || failures=$((failures + 1))
    done

    if (( failures > 0 )); then
        echo "❌ ${target_cluster}: ${failures} secret(s) FAILED to sync"
    else
        echo "✅ ${target_cluster}: all secrets synced"
    fi
    return "${failures}"
}

for bin in kubectl jq; do
    if ! command -v "${bin}" &> /dev/null; then
        echo "❌ Error: ${bin} not found"
        exit 1
    fi
done

TARGET_CLUSTER="${1:-}"
TARGETS=("${DOWNSTREAM_CLUSTERS[@]}")

if [[ -n "${TARGET_CLUSTER}" ]]; then
    if [[ ! " ${DOWNSTREAM_CLUSTERS[*]} " =~ " ${TARGET_CLUSTER} " ]]; then
        echo "❌ Error: ${TARGET_CLUSTER} is not a downstream cluster."
        echo "   Valid downstream clusters: ${DOWNSTREAM_CLUSTERS[*]}"
        exit 1
    fi
    TARGETS=("${TARGET_CLUSTER}")
else
    echo "📋 Syncing certificates from ${SOURCE_CLUSTER} to all downstream clusters..."
fi

FAILED_CLUSTERS=()
for cluster in "${TARGETS[@]}"; do
    sync_to_cluster "${cluster}" || FAILED_CLUSTERS+=("${cluster}")
done

echo ""
if (( ${#FAILED_CLUSTERS[@]} > 0 )); then
    echo "❌ Certificate sync FAILED for ${#FAILED_CLUSTERS[@]}/${#TARGETS[@]} cluster(s): ${FAILED_CLUSTERS[*]}"
    exit 1
fi
echo "✅ Certificate sync complete for ${#TARGETS[@]} cluster(s)"
